# <span style="color:darkblue"> QTM 151 - Quiz 3 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your Emory ID as a string below

In [59]:
# Write your answer here
ID = 2512750
print(ID)

2512750

<font size = "5" >
This quiz is open book 

- You can use the lecture notes and the internet
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"


**By printing the message, you acknowledge that you will abide by Emory's code of conduct.**

In [60]:
# Write your answer here:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [61]:
# Write your answer here
import numpy as np
import pandas as pd


<font size = "5">

(a) Replace the values of a column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Print the list with the unique values that are not numeric in the column "positionText"
- Replace the non-numerica values ("R" and "N") with ```np.nan``` (missing value) in the column "positionText"
- Create a new column "positionNumeric" that converts the modified "positionText" column from string to numeric using ```pd.to_numeric()```

HINT: See the example in Lecture 12

In [68]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")

subset = sprint_results.query("positionText.str.isnumeric() == False")

list_unique = pd.unique(subset["positionText"])

print(list_unique)

list_old = ['R','N']
list_new = [np.nan, np.nan]

sprint_results["positionText"] = sprint_results["positionText"].replace(list_old, list_new)

sprint_results['positionNumeric'] = pd.to_numeric(sprint_results['positionText'], errors='coerce')

print(sprint_results)
print(sprint_results.dtypes)

['R' 'N']
     resultId  raceId  driverId  constructorId  number  grid position  \
0           1    1061       830              9      33     2        1
1           2    1061         1            131      44     1        2
2           3    1061       822            131      77     3        3
3           4    1061       844              6      16     4        4
4           5    1061       846              1       4     6        5
..        ...     ...       ...            ...     ...   ...      ...
115       116    1095       840            117      18    15       16
116       117    1095       839            214      31     6       17
117       118    1095         4            214      14     7       18
118       119    1095       849              3       6    16       19
119       120    1095       848              3      23    11       \N

    positionText  positionOrder  points  laps       time milliseconds  \
0              1              1       3    17  25:38.426      1538426
1              2              2       2    17     +1.430      1539856
2              3              3       1    17     +7.502      1545928
3              4              4       0    17    +11.278      1549704
4              5              5       0    17    +24.111      1562537
..           ...            ...     ...   ...        ...          ...
115           16             16       0    24    +50.700      1862007
116           17             17       0    24    +51.756      1863063
117           18             18       0    24    +53.985      1865292
118           19             19       0    24  +1:16.850      1888157
119          NaN             20       0    12         \N           \N

    fastestLap fastestLapTime  statusId  positionNumeric
0           14       1:30.013         1              1.0
1           17       1:29.937         1              2.0
2           17       1:29.958         1              3.0
3           16       1:30.163         1              4.0
4           16       1:30.566         1              5.0
..         ...            ...       ...              ...
115          4       1:15.425         1             16.0
116          5       1:16.097         1             17.0
117          5       1:14.764         1             18.0
118          4       1:16.525         1             19.0
119          4       1:15.998        31              NaN

[120 rows x 17 columns]
resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number               int64
grid                 int64
position            object
positionText        object
positionOrder        int64
points               int64
laps                 int64
time                object
milliseconds        object
fastestLap          object
fastestLapTime      object
statusId             int64
positionNumeric    float64
dtype: object

<font size = "5">

(b) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" with the following categories

$\qquad$ ``` ["1950-1974","1975-1999","2000-onwards"] ```

- Display the new "year_brackets" variable

$\qquad$ HINT: Use the "pd.cut()" command. See Lecture 12 (check the note in the example!)

In [63]:
# Write your own code
races = pd.read_csv("data_raw/races.csv")
year = ["1950", "1974", "1999", "2500"]
year_brackets = ["1950-1974", "1975-1999", "2000-onwards"]
races['year_bracket'] = pd.cut(races['year'], bins= year, labels= year_brackets)
print(races)
display(races['year_bracket'])

      raceId  year  round  circuitId                      name        date  \
0          1  2009      1          1     Australian Grand Prix  2009-03-29
1          2  2009      2          2      Malaysian Grand Prix  2009-04-05
2          3  2009      3         17        Chinese Grand Prix  2009-04-19
3          4  2009      4          3        Bahrain Grand Prix  2009-04-26
4          5  2009      5          4        Spanish Grand Prix  2009-05-10
...      ...   ...    ...        ...                       ...         ...
1097    1116  2023     19         69  United States Grand Prix  2023-10-22
1098    1117  2023     20         32    Mexico City Grand Prix  2023-10-29
1099    1118  2023     21         18      SÃ£o Paulo Grand Prix  2023-11-05
1100    1119  2023     22         80      Las Vegas Grand Prix  2023-11-19
1101    1120  2023     23         24      Abu Dhabi Grand Prix  2023-11-26

          time                                                url    fp1_date  \
0     06:00:00  http://en.wikipedia.org/wiki/2009_Australian_G...          \N
1     09:00:00  http://en.wikipedia.org/wiki/2009_Malaysian_Gr...          \N
2     07:00:00  http://en.wikipedia.org/wiki/2009_Chinese_Gran...          \N
3     12:00:00  http://en.wikipedia.org/wiki/2009_Bahrain_Gran...          \N
4     12:00:00  http://en.wikipedia.org/wiki/2009_Spanish_Gran...          \N
...        ...                                                ...         ...
1097  19:00:00  https://en.wikipedia.org/wiki/2023_United_Stat...  2023-10-20
1098  20:00:00  https://en.wikipedia.org/wiki/2023_Mexico_City...  2023-10-27
1099  17:00:00  https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...  2023-11-03
1100  06:00:00  https://en.wikipedia.org/wiki/2023_Las_Vegas_G...  2023-11-17
1101  13:00:00  https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...  2023-11-24

      fp1_time    fp2_date  fp2_time    fp3_date  fp3_time  quali_date  \
0           \N          \N        \N          \N        \N          \N
1           \N          \N        \N          \N        \N          \N
2           \N          \N        \N          \N        \N          \N
3           \N          \N        \N          \N        \N          \N
4           \N          \N        \N          \N        \N          \N
...        ...         ...       ...         ...       ...         ...
1097  17:30:00  2023-10-21  18:00:00          \N        \N  2023-10-20
1098  18:30:00  2023-10-27  22:00:00  2023-10-28  17:30:00  2023-10-28
1099  14:30:00  2023-11-04  14:30:00          \N        \N  2023-11-03
1100  04:30:00  2023-11-17  08:00:00  2023-11-18  04:30:00  2023-11-18
1101  09:30:00  2023-11-24  13:00:00  2023-11-25  10:30:00  2023-11-25

     quali_time sprint_date sprint_time  year_bracket
0            \N          \N          \N  2000-onwards
1            \N          \N          \N  2000-onwards
2            \N          \N          \N  2000-onwards
3            \N          \N          \N  2000-onwards
4            \N          \N          \N  2000-onwards
...         ...         ...         ...           ...
1097   21:00:00  2023-10-21    22:00:00  2000-onwards
1098   21:00:00          \N          \N  2000-onwards
1099   18:00:00  2023-11-04    18:30:00  2000-onwards
1100   08:00:00          \N          \N  2000-onwards
1101   14:00:00          \N          \N  2000-onwards

[1102 rows x 19 columns]

0       2000-onwards
1       2000-onwards
2       2000-onwards
3       2000-onwards
4       2000-onwards
            ...
1097    2000-onwards
1098    2000-onwards
1099    2000-onwards
1100    2000-onwards
1101    2000-onwards
Name: year_bracket, Length: 1102, dtype: category
Categories (3, object): ['1950-1974' < '1975-1999' < '2000-onwards']

<font size = "5">

(c) Aggregate and query

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Subset the observations for 'constructorId == 3' using ```.query()```
- Obtain the sum of "laps" by "driverId" using ``` .groupby().agg() ```
- Subset the drivers with a sum of laps $\ge 40$
- Store the results of all these operations in a dataframe ```sprint_results_agg ```
- Display the ```sprint_results_agg``` dataframe
- Provide a one-sentence explanation of the information in the ```sprint_results_agg ``` table

In [64]:
# Write your own code

#sprint_results_subset = sprint_results.query("constructorId == 3")
#sprint_results_sum = sprint_results_subset.groupby("driverId")["laps"].agg("sum")
#sprint_results_agg = sprint_results_sum[sprint_results_sum >= 40]
#sprint_results_agg = sprint_results_agg.reset_index() 

sprint_results_agg = (pd.read_csv("data_raw/sprint_results.csv")
    .query("constructorId == 3")
    .groupby("driverId")["laps"]
    .agg("sum")
    .reset_index()
    .query("laps >= 40"))

print(sprint_results_agg)

print("This table shows the driverIds and the corresponding sums of laps in the 'sprint_results' dataset for when constructorId is 3 where the sum of laps is greater than or equal to 40.")

   driverId  laps
0       847    59
1       848    56
2       849   127
This table shows the driverIds and the corresponding sums of laps in the 'sprint_results' dataset for when constructorId is 3 where the sum of laps is greater than or equal to 40.

<font size = "5">

(d) Aggregate and sort

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Obtain the sum of "laps" by "driverId" using ``` .groupby().agg() ```
- Sort the teams in descending order using of the sum of laps using ``` .sort_values() ```
- Display your results

In [65]:
# Write your own code

#sprint_results_sum = sprint_results_subset.groupby("driverId")["laps"].agg("sum")
#sprint_results_sorted = sprint_results_sum.sort_values(ascending=False)
#display(sprint_results_sum)

sprint_results_agg = (pd.read_csv("data_raw/sprint_results.csv")
    .groupby("driverId")["laps"]
    .agg("sum")
    .reset_index()
    .sort_values(by="laps", ascending=False))

display(sprint_results_agg)

    driverId  laps
0          1   127
10       832   127
22       854   127
20       852   127
19       849   127
17       847   127
16       846   127
15       844   127
11       839   127
12       840   127
9        830   127
7        822   127
6        817   127
5        815   126
4         20   125
14       842   109
1          4   104
8        825    68
13       841    59
21       853    59
18       848    56
23       855    47
2          8    41
3          9    18

<font size = "5">

(e) Rename column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Rename the column "points" to "points_sprint"
- Display the dataframe columns

HINT: Create a dictionary and use ```.rename(columns = ...)``` See Lecture 14

In [66]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")
sprint_results = sprint_results.rename(columns={"points": "points_sprint"})

print(sprint_results.columns)

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points_sprint', 'laps',
       'time', 'milliseconds', 'fastestLap', 'fastestLapTime', 'statusId'],
      dtype='object')

<font size = "5">

(f) Merge dataset

<font size = "3">

- Import the "data_raw/sprint_results.csv" and "data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using "sprint_results" as the primary dataset (left), and "constructors" as the secondary dataset (right), merging on the column "constructorId"
- To get full points **ONLY** merge the "url" column from the secondary dataset (not all the columns)
- Display the resulting dataframe 


HINT: Use ```[[...]]``` to extract a subset of columns from the secondary dataset before merging, including the "constructorId" column

In [67]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")
constructors = pd.read_csv("data_raw/constructors.csv")

merge = pd.merge(sprint_results, constructors[["constructorId", "url"]], on = "constructorId")

print(merge)

     resultId  raceId  driverId  constructorId  number  grid position  \
0           1    1061       830              9      33     2        1
1          20    1061       815              9      11     5       \N
2          22    1065       830              9      33     3        2
3          29    1065       815              9      11     9        9
4          42    1071       830              9      33     1        2
..        ...     ...       ...            ...     ...   ...      ...
115        70    1077       854            210      47    12       10
116        87    1084       825            210      20     6        7
117        89    1084       854            210      47     7        9
118       108    1095       825            210      20     1        8
119       112    1095       854            210      47    20       12

    positionText  positionOrder  points  laps       time milliseconds  \
0              1              1       3    17  25:38.426      1538426
1              R             20       0    16         \N           \N
2              2              2       2    18     +2.325      1676403
3              9              9       0    18    +31.680      1705758
4              2              2       2    24     +1.170      1750729
..           ...            ...     ...   ...        ...          ...
115           10             10       0    21    +33.773      1873340
116            7              7       2    23    +34.539      1624598
117            9              9       0    23    +37.163      1627222
118            8              8       1    24    +28.768      1840075
119           12             12       0    24    +41.159      1852466

    fastestLap fastestLapTime  statusId  \
0           14       1:30.013         1
1            6       1:31.465        76
2            9       1:23.502         1
3           12       1:24.211         1
4            9       1:12.114         1
..         ...            ...       ...
115         15       1:20.567         1
116          4       1:09.232         1
117          4       1:09.457         1
118          2       1:15.110         1
119          5       1:15.771         1

                                              url
0    http://en.wikipedia.org/wiki/Red_Bull_Racing
1    http://en.wikipedia.org/wiki/Red_Bull_Racing
2    http://en.wikipedia.org/wiki/Red_Bull_Racing
3    http://en.wikipedia.org/wiki/Red_Bull_Racing
4    http://en.wikipedia.org/wiki/Red_Bull_Racing
..                                            ...
115     http://en.wikipedia.org/wiki/Haas_F1_Team
116     http://en.wikipedia.org/wiki/Haas_F1_Team
117     http://en.wikipedia.org/wiki/Haas_F1_Team
118     http://en.wikipedia.org/wiki/Haas_F1_Team
119     http://en.wikipedia.org/wiki/Haas_F1_Team

[120 rows x 17 columns]